" All system-wide defaults are set in $VIMRUNTIME/debian.vim (usually just
" /usr/share/vim/vimcurrent/debian.vim) and sourced by the call to :runtime
" you can find below.  If you wish to change any of those settings, you should
" do it in this file (/etc/vim/vimrc), since debian.vim will be overwritten
" everytime an upgrade of the vim packages is performed.  It is recommended to
" make changes after sourcing debian.vim since it alters the value of the
" 'compatible' option.

" This line should not be removed as it ensures that various options are
" properly set to work with the Vim-related packages available in Debian.
runtime! debian.vim

" Uncomment the next line to make Vim more Vi-compatible
" NOTE: debian.vim sets 'nocompatible'.  Setting 'compatible' changes numerous
" options, so any other options should be set AFTER setting 'compatible'.
"set compatible

" Vim5 and later versions support syntax highlighting. Uncommenting the next
" line enables syntax highlighting by default.
syntax on

" If using a dark background within the editing area and syntax highlighting
" turn on this option as well
"set background=dark

" Uncomment the following to have Vim jump to the last position when
" reopening a file
if has("autocmd")
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif

" Uncomment the following to have Vim load indentation rules and plugins
" according to the detected filetype.
if has("autocmd")
  filetype plugin indent on
endif

filetype plugin on
" The following are commented out as they cause vim to behave a lot
" differently from regular Vi. They are highly recommended though.
set showcmd		" Show (partial) command in status line.
set showmatch		" Show matching brackets.
"set ignorecase		" Do case insensitive matching
set smartcase		" Do smart case matching
"set incsearch		" Incremental search
"set autowrite		" Automatically save before commands like :next and :make
"set hidden             " Hide buffers when they are abandoned
set mouse=a		" Enable mouse usage (all modes)
set nu			" Enable line number	
set ts=8		" set Tab 8 Space
set autoindent		" set auto indent
set cindent		" set c/c++ indent
set autoread		" auto read while file was edited
set cursorline		" set cursor line
set autochdir		" auto ch PWD to current file's path

" Source a global configuration file if available
if filereadable("/etc/vim/vimrc.local")
  source /etc/vim/vimrc.local
endif

"taglist
let Tlist_Show_One_File=1
"let Tlist_WinWidth=20
let Tlist_Exit_OnlyWindow=1
let Tlist_Auto_Open=1
let Tlist_Use_Right_Window=1

"NERDTree
map <F3> :NERDTreeToggle<cr>
imap <F3><ESC> :NERDTreeToggle<cr>
"let NERDTreeWinSize=20
let NERDTreeChDirMode=2
"cursor will be move to NERDTree while it start
"move back to vim 
autocmd vimenter * NERDTree 
wincmd w
autocmd vimenter * wincmd w

map <F4> :NERDTreeToggle<cr>:TlistToggle<CR>

map tc :TlistClose<cr>
map to :TlistOpen<cr>
map <F1> :set paste<cr><Esc>ggO/*<CR> *<CR> * Authored by Liu Peng on:<Esc>:read !date <CR>kJ$a<CR> *<CR> * @desc:<CR> *<CR> * @func:<CR>**/<Esc>:set nopaste<cr>
map <F2> :set paste<cr><Esc>O/*<CR> * Funcion<Tab>:<CR> *<CR> * Author<Tab>:<CR> *<CR> * arguments<Tab>:<CR> * return<Tab>:<CR>**/<Esc>:set nopaste<cr>

autocmd WinEnter * call s:CloseIfOnlyNerdTreeLeft()

" Close all open buffers on entering a window if the only
" buffer that's left is the NERDTree buffer
function! s:CloseIfOnlyNerdTreeLeft()
    if exists("t:NERDTreeBufName")
        if bufwinnr(t:NERDTreeBufName) != -1
            if winnr("$") == 1
                q
            elseif winnr("$") == 2
                if bufwinnr("__Tag_List__") != -1
                    q
		    q
                endif
            endif
        endif
    endif
endfunction


"cs add /home/liupeng/extend/360/RTL-360/user/cscope.out /home/liupeng/extend/360/RTL-360/user/

set tags+=/home/liupeng/extend/360/RTL-360/user/tags
set tags+=/home/liupeng/extend/360/RTL-360/linux/linux/tags
"set tags+=/home/liupeng/extend/360/RTL-360-151118/user/tags
"set tags+=/home/liupeng/extend/360/RTL-360-WIFI-SHARE/user/tags
"set tags+=/home/liupeng/extend/360/RTL-360-P0/user/tags
set tags+=/home/liupeng/extend/book/tags
"set tags+=/home/liupeng/extend/src/tags
set tags+=/home/liupeng/program/tags

" tab
map <F5> : tabp<CR>
map <F6> : tabn<CR>

" quit, close all tab
map Q : qall<CR>

